.TH LOA-HELP 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
help \- print help or command\-specific help
.SH SYNOPSIS
alexandria> help [command]
.SH DESCRIPTION
print help or command\-specific help.
.SH EXAMPLES
.TP
alexandria> help progress
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
