.TH LOA-SNAPSHOT-RESTORE 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
snapshot restore \- restore state from snapshot
.SH SYNOPSIS
alexandria> snapshot restore
.SH DESCRIPTION
restore state from snapshot.
.SH EXAMPLES
.TP
alexandria> snapshot restore
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
