.TH LOA-LANGUAGE 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
language \- set language to German/English/French/Japanese by reference
.SH SYNOPSIS
alexandria> language
.SH DESCRIPTION
set language to German/English/French/Japanese by reference.
.SH EXAMPLES
.TP
alexandria> language
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
