.TH LOA-PRACTICE-LOG 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
practice log \- log sheet\-music practice minutes and bpm
.SH SYNOPSIS
alexandria> practice log
.SH DESCRIPTION
log sheet\-music practice minutes and bpm.
.SH EXAMPLES
.TP
alexandria> practice log
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
