.TH LOA-BULK-EDIT 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
bulk edit \- bulk\-update language/location/genre/tags/series on filtered items
.SH SYNOPSIS
alexandria> bulk edit
.SH DESCRIPTION
bulk\-update language/location/genre/tags/series on filtered items.
.SH EXAMPLES
.TP
alexandria> bulk edit
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
