.TH LOA-READING-ADD 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
reading add \- add an item to reading list by reference
.SH SYNOPSIS
alexandria> reading add
.SH DESCRIPTION
add an item to reading list by reference.
.SH EXAMPLES
.TP
alexandria> reading add
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
