.TH LOA-DEDUP-MERGE 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
dedup merge \- merge two duplicate items
.SH SYNOPSIS
alexandria> dedup merge
.SH DESCRIPTION
merge two duplicate items.
.SH EXAMPLES
.TP
alexandria> dedup merge
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
