.TH LOA-SHEET-STATS 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
sheet stats \- show sheet music specific statistics
.SH SYNOPSIS
alexandria> sheet stats
.SH DESCRIPTION
show sheet music specific statistics.
.SH EXAMPLES
.TP
alexandria> sheet stats
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
