.TH LOA-SMART-ADD 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
smart add \- create or update a smart list
.SH SYNOPSIS
alexandria> smart add
.SH DESCRIPTION
create or update a smart list.
.SH EXAMPLES
.TP
alexandria> smart add
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
