.TH LOA-FIND-AUTHOR 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
find author \- search items by author
.SH SYNOPSIS
alexandria> find author
.SH DESCRIPTION
search items by author.
.SH EXAMPLES
.TP
alexandria> find author
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
