.TH LOA-SORT-BY 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
sort by \- sort by title | author | type | year | pages | language
.SH SYNOPSIS
alexandria> sort by <field>
.SH DESCRIPTION
sort by title | author | type | year | pages | language.
.SH EXAMPLES
.TP
alexandria> sort by language
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
