.TH LOA-FIND-COMPOSER 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
find composer \- search sheet music by composer
.SH SYNOPSIS
alexandria> find composer
.SH DESCRIPTION
search sheet music by composer.
.SH EXAMPLES
.TP
alexandria> find composer bach
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
