.TH LOA-SERIES-SET 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
series set \- set series name/index for one item
.SH SYNOPSIS
alexandria> series set
.SH DESCRIPTION
set series name/index for one item.
.SH EXAMPLES
.TP
alexandria> series set
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
