.TH LOA-MAN 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
man \- show bundled man page for a specific command
.SH SYNOPSIS
alexandria> man <command>
.SH DESCRIPTION
show bundled man page for a specific command.
.SH EXAMPLES
.TP
alexandria> man reading add
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
