.TH LOA-CALENDAR-LIST 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
calendar list \- list scheduled sessions for one date
.SH SYNOPSIS
alexandria> calendar list [date]
.SH DESCRIPTION
list scheduled sessions for one date.
.SH EXAMPLES
.TP
alexandria> calendar list 2026\-04\-01
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
