.TH LOA-INBOX-ADD 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
inbox add \- quick\-capture unstructured item idea
.SH SYNOPSIS
alexandria> inbox add
.SH DESCRIPTION
quick\-capture unstructured item idea.
.SH EXAMPLES
.TP
alexandria> inbox add
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
