.TH LOA-READING-REMOVE 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
reading remove \- remove from reading list by reference
.SH SYNOPSIS
alexandria> reading remove
.SH DESCRIPTION
remove from reading list by reference.
.SH EXAMPLES
.TP
alexandria> reading remove
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
