.TH LOA-LIST-TAG 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
list tag \- list items by tag
.SH SYNOPSIS
alexandria> list tag <name>
.SH DESCRIPTION
list items by tag.
.SH EXAMPLES
.TP
alexandria> list tag classics
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
