.TH LOA-METADATA-AUTOFILL 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
metadata autofill \- fetch missing metadata from online sources with confirmation
.SH SYNOPSIS
alexandria> metadata autofill [reference|all]
.SH DESCRIPTION
fetch missing metadata from online sources with confirmation.
.SH EXAMPLES
.TP
alexandria> metadata autofill all
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
