.TH LOA-SNAPSHOT-LIST 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
snapshot list \- list available snapshots
.SH SYNOPSIS
alexandria> snapshot list
.SH DESCRIPTION
list available snapshots.
.SH EXAMPLES
.TP
alexandria> snapshot list
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
