.TH LOA-PRACTICE 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
practice \- set sheet music practice status by reference
.SH SYNOPSIS
alexandria> practice
.SH DESCRIPTION
set sheet music practice status by reference.
.SH EXAMPLES
.TP
alexandria> practice
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
