.TH LOA-FIND-NOTES 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
find notes \- search full\-text notes
.SH SYNOPSIS
alexandria> find notes
.SH DESCRIPTION
search full\-text notes.
.SH EXAMPLES
.TP
alexandria> find notes
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
