.TH LOA-GOAL-SET-YEARLY 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
goal set yearly \- set yearly reading goal
.SH SYNOPSIS
alexandria> goal set yearly
.SH DESCRIPTION
set yearly reading goal.
.SH EXAMPLES
.TP
alexandria> goal set yearly
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
