.TH LOA-LIST-READ 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
list read \- list only read items
.SH SYNOPSIS
alexandria> list read
.SH DESCRIPTION
list only read items.
.SH EXAMPLES
.TP
alexandria> list read
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
