.TH LOA-STATS 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
stats \- show collection and reading stats
.SH SYNOPSIS
alexandria> stats
.SH DESCRIPTION
show collection and reading stats.
.SH EXAMPLES
.TP
alexandria> stats
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
