.TH LOA-READING-SMART-GENERATE 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
reading smart generate \- replace reading list with smart recommendations
.SH SYNOPSIS
alexandria> reading smart generate [count]
.SH DESCRIPTION
replace reading list with smart recommendations.
.SH EXAMPLES
.TP
alexandria> reading smart generate 8
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
