.TH LOA-TAG-CLEAR 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
tag clear \- clear all tags from an item
.SH SYNOPSIS
alexandria> tag clear
.SH DESCRIPTION
clear all tags from an item.
.SH EXAMPLES
.TP
alexandria> tag clear
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
