.TH LOA-SNAPSHOT-CREATE 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
snapshot create \- create named restore snapshot
.SH SYNOPSIS
alexandria> snapshot create [name]
.SH DESCRIPTION
create named restore snapshot.
.SH EXAMPLES
.TP
alexandria> snapshot create before\-import
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
