.TH LOA-INBOX-REMOVE 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
inbox remove \- remove inbox item
.SH SYNOPSIS
alexandria> inbox remove
.SH DESCRIPTION
remove inbox item.
.SH EXAMPLES
.TP
alexandria> inbox remove
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
