.TH LOA-FIND-TITLE 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
find title \- search items by title
.SH SYNOPSIS
alexandria> find title
.SH DESCRIPTION
search items by title.
.SH EXAMPLES
.TP
alexandria> find title
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
