.TH LOA-LIST-INSTRUMENT 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
list instrument \- list sheet music by instrumentation
.SH SYNOPSIS
alexandria> list instrument <name>
.SH DESCRIPTION
list sheet music by instrumentation.
.SH EXAMPLES
.TP
alexandria> list instrument piano
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
