.TH LOA-LIST-TAG 1 "2026-03-15" "Library Of Alexandria" "User Commands"
.SH NAME
list tag \- Show books by tag
.SH SYNOPSIS
alexandria> list tag <name>
.SH DESCRIPTION
.TP
Filters books by a tag value.
.TP
Tag matching is case-insensitive.
.SH EXAMPLES
.TP
alexandria> list tag school
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
