.TH LOA-INTERESTS-SET 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
interests set \- set smart recommendation interests
.SH SYNOPSIS
alexandria> interests set
.SH DESCRIPTION
set smart recommendation interests.
.SH EXAMPLES
.TP
alexandria> interests set
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
