.TH LOA-TAG-SET 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
tag set \- replace all tags on an item
.SH SYNOPSIS
alexandria> tag set
.SH DESCRIPTION
replace all tags on an item.
.SH EXAMPLES
.TP
alexandria> tag set
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
