.TH LOA-LIST-UNREAD 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
list unread \- list only unread items
.SH SYNOPSIS
alexandria> list unread
.SH DESCRIPTION
list only unread items.
.SH EXAMPLES
.TP
alexandria> list unread
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
