.TH LOA-LIST-INSTRUMENT 1 "2026-03-23" "Library Of Alexandria" "User Commands"
.SH NAME
list instrument \- Show sheet music by instrumentation
.SH SYNOPSIS
alexandria> list instrument <name>
.SH DESCRIPTION
Filters \fBSheetMusic\fR entries where instrumentation contains the given text.
.br
Matching is case-insensitive and supports partial input.
.SH EXAMPLES
.TP
alexandria> list instrument piano
.TP
alexandria> list instrument string quartet
.SH SEE ALSO
loa(1), loa-list-sheet(1), loa-find-composer(1), loa-details(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
