.TH LOA-INTERESTS-CLEAR 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
interests clear \- clear smart recommendation interests
.SH SYNOPSIS
alexandria> interests clear
.SH DESCRIPTION
clear smart recommendation interests.
.SH EXAMPLES
.TP
alexandria> interests clear
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
