.TH LOA-READING-LIST 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
reading list \- show reading list
.SH SYNOPSIS
alexandria> reading list
.SH DESCRIPTION
show reading list.
.SH EXAMPLES
.TP
alexandria> reading list
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
