.TH LOA-PRACTICE-TEMPO 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
practice tempo \- set tempo target bpm for sheet music
.SH SYNOPSIS
alexandria> practice tempo
.SH DESCRIPTION
set tempo target bpm for sheet music.
.SH EXAMPLES
.TP
alexandria> practice tempo
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
