.TH LOA-GOAL-CLEAR-MONTHLY 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
goal clear monthly \- clear monthly goal
.SH SYNOPSIS
alexandria> goal clear monthly
.SH DESCRIPTION
clear monthly goal.
.SH EXAMPLES
.TP
alexandria> goal clear monthly
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
