.TH LOA-HISTORY 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
history \- show command history
.SH SYNOPSIS
alexandria> history
.SH DESCRIPTION
show command history.
.SH EXAMPLES
.TP
alexandria> history
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
