.TH LOA-PROFILE-USE 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
profile use \- switch active profile
.SH SYNOPSIS
alexandria> profile use <name>
.SH DESCRIPTION
switch active profile.
.SH EXAMPLES
.TP
alexandria> profile use school
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
