.TH LOA-DEDUP-SCAN 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
dedup scan \- scan for likely duplicate items
.SH SYNOPSIS
alexandria> dedup scan
.SH DESCRIPTION
scan for likely duplicate items.
.SH EXAMPLES
.TP
alexandria> dedup scan
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
