.TH LOA-READING-SMART-APPEND 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
reading smart append \- append smart recommendations to reading list
.SH SYNOPSIS
alexandria> reading smart append [count]
.SH DESCRIPTION
append smart recommendations to reading list.
.SH EXAMPLES
.TP
alexandria> reading smart append 5
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
