.TH LOA-MARK-READ 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
mark read \- mark an item as read by reference
.SH SYNOPSIS
alexandria> mark read
.SH DESCRIPTION
mark an item as read by reference.
.SH EXAMPLES
.TP
alexandria> mark read
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
