.TH LOA-COMPACT 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
compact \- toggle compact table mode
.SH SYNOPSIS
alexandria> compact [on|off|toggle]
.SH DESCRIPTION
toggle compact table mode.
.SH EXAMPLES
.TP
alexandria> compact toggle
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
