.TH LOA-INBOX-DONE 1 "2026-03-31" "Library Of Alexandria" "User Commands"
.SH NAME
inbox done \- mark inbox item as done
.SH SYNOPSIS
alexandria> inbox done
.SH DESCRIPTION
mark inbox item as done.
.SH EXAMPLES
.TP
alexandria> inbox done
.SH SEE ALSO
loa(1)
.SH AUTHOR
Generated for the Library Of Alexandria project.
